In [10]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [11]:
import numpy as np

In [12]:
np.__version__

'1.26.4'

In [14]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32


In [15]:
#WAP to Give me the dtype as float instead of int but dont give direct float in numbers
#while declaring

In [16]:
arr=np.array([1,2,3,4,5,6],dtype='float')
print(arr)
print(type(arr))
print(arr.dtype)

[1. 2. 3. 4. 5. 6.]
<class 'numpy.ndarray'>
float64


In [17]:
arr=np.array([1,3,4,5,'charan',2-9j,32.])
print(arr)
print(type(arr))
print(arr.dtype)

['1' '3' '4' '5' 'charan' '(2-9j)' '32.0']
<class 'numpy.ndarray'>
<U64


In [27]:
arr=np.array([1,3,4,0,0,5,6.])
print(arr)
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.count_nonzero(arr))
print(np.quantile(arr,.34))
#Assignment question justify that 1.08 how its 34 percent quantile ?

[1. 3. 4. 0. 0. 5. 6.]
19.0
2.7142857142857144
0.0
6.0
3.0
5
1.08


In [32]:
arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr)
print()
print(arr[0][0])
print(arr[2][0])
print(arr[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

1
7
2


In [33]:
arr=np.array([1,2,3,4,5,6],dtype='str')
print(arr)
print(type(arr))
print(arr.dtype)

['1' '2' '3' '4' '5' '6']
<class 'numpy.ndarray'>
<U1


In [34]:
arr=np.zeros([2,4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
arr=np.zeros([2,4],dtype=int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
arr=np.zeros([3,3],dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
arr=np.ones([3,3],dtype=int)
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [38]:
arr=np.twos([3,3],dtype=int)
arr

AttributeError: module 'numpy' has no attribute 'twos'

In [39]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.ones_like(arr)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [41]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [42]:
np.identity(1)

array([[1.]])

In [43]:
np.random.randn(3,4)

array([[-3.55611766e-01, -9.04999996e-01, -8.07244624e-02,
         1.73546396e+00],
       [-7.38649357e-01, -4.81865295e-01, -1.37349341e-04,
         1.20451957e+00],
       [-6.48975316e-01, -6.13121129e-01, -1.09715990e-01,
        -5.57826886e-01]])

In [44]:
range(5)

range(0, 5)

In [45]:
for i in range(5):
    print(i,end=' ')

0 1 2 3 4 

In [47]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [48]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [50]:
arr=np.array([10,20,30,40,50])
print(arr)
print(arr.shape)
# Assignment 2 : Infer what is that value (5,)

[10 20 30 40 50]
(5,)


In [54]:
t=(1)
type(t)

int

In [55]:
g=(1,)
type(g)

tuple

In [57]:
arr=np.arange(12)
print(arr)
print(arr.shape)
print("1D or 2D",np.ndim(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
1D or 2D 1


In [58]:
arr=np.arange(12).reshape(6,2)
print(arr)
print(arr.shape)
print("1D or 2D",np.ndim(arr))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
(6, 2)
1D or 2D 2


In [59]:
arr=np.arange(12).reshape(2,2,3) #2 arrays 2 rows 2 columns
print(arr)
print(arr.shape)
print("1D or 2D",np.ndim(arr))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
1D or 2D 3


In [60]:
#ufunc 
#they support board casting in Deep learning & Neural Networks

In [61]:
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
arr+5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
arr*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [65]:
arr1=np.arange(15).reshape(5,3)
arr2=np.arange(5).reshape(5,1)
print(arr1)
print(arr2)
print(arr1*arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [27 30 33]
 [48 52 56]]


In [66]:
a=np.array([[7,5,-3],[3,-5,2],[5,3,-7]])
b=np.array([16,-8,0])
np.linalg.solve(a,b)

array([1., 3., 2.])

In [67]:
arr=np.array([[1,2],[3,4]])
np.linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [68]:
arr=np.array([[1,2],[3,4]])
np.linalg.det(arr)

-2.0000000000000004

In [70]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(arr)

0.0

# Pandas

In [71]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable


In [72]:
import pandas as pd
pd.__version__

'1.5.3'

In [73]:
pd.Series([2,3,4,5,1,32])

0     2
1     3
2     4
3     5
4     1
5    32
dtype: int64

In [74]:
s=pd.Series([2,3,4,1,5,32])
print(s)
print(type(s))

0     2
1     3
2     4
3     1
4     5
5    32
dtype: int64
<class 'pandas.core.series.Series'>


In [75]:
pd.Series([10,12,8],index=[100,200,300])

100    10
200    12
300     8
dtype: int64

In [76]:
pd.Series([10,12,8],index=['A','B','C'])

A    10
B    12
C     8
dtype: int64

In [77]:
s=pd.Series([10,12,8],index=['A',100,41.2212])
s

A          10
100        12
41.2212     8
dtype: int64

In [78]:
s.reset_index()

index   0
0        A  10
1      100  12
2  41.2212   8

In [79]:
s1=pd.Series([99,100,95],index=['Kar','Ken','Kane'])
print(s1)
print(s1.reset_index())

Kar      99
Ken     100
Kane     95
dtype: int64
  index    0
0   Kar   99
1   Ken  100
2  Kane   95


# Indexers loc  & iloc

In [80]:
data=pd.Series(['a','b','c'],index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [81]:
data[1]

'a'

In [83]:
data[3]

'b'

In [84]:
data[5]

'c'

In [85]:
data.iloc[2]

'c'

In [86]:
data.iloc[0]

'a'

In [87]:
data.iloc[1]

'b'